-- ###########################################################################################
--                          RENDER-MARKDOWN CONFIGURATION
-- ###########################################################################################

return {
	"MeanderingProgrammer/render-markdown.nvim",
	opts = {
		file_types = { "markdown", "vimwiki" },
		win_options = {
			conceallevel = {
				default = vim.api.nvim_get_option_value("conceallevel", {}),
				rendered = 2,
			},
			concealcursor = {
				default = vim.api.nvim_get_option_value("concealcursor", {}),
				rendered = "", -- Always reveal on cursor line
			},
		},
		heading = {
			enabled = true,
			render_modes = false,
			atx = true,
			setext = false,
			sign = true,
			icons = { "󰼏 ", "󰼐 ", "󰼑 ", "󰼒 ", "󰼓 ", "󰼔 " },
			position = "inline",
			signs = { "󰫎 " },
			width = { "full", "full", "block", "block", "block", "block" },
			left_margin = 0,
			left_pad = 0,
			right_pad = 0,
			min_width = 80,
			border = false,
			border_virtual = false,
			border_prefix = true,
			above = "▄",
			below = "▀",
			backgrounds = {
				"RenderMarkdownH1Bg",
				"RenderMarkdownH2Bg",
				"RenderMarkdownH3Bg",
				"RenderMarkdownH4Bg",
				"RenderMarkdownH5Bg",
				"RenderMarkdownH6Bg",
			},
			foregrounds = {
				"RenderMarkdownH1",
				"RenderMarkdownH2",
				"RenderMarkdownH3",
				"RenderMarkdownH4",
				"RenderMarkdownH5",
				"RenderMarkdownH6",
			},
		},
		quote = {
			enabled = true,
			render_modes = false,
			icon = "║",
			repeat_linebreak = false,
			highlight = {
				"RenderMarkdownQuote1",
				"RenderMarkdownQuote2",
				"RenderMarkdownQuote3",
				"RenderMarkdownQuote4",
				"RenderMarkdownQuote5",
				"RenderMarkdownQuote6",
			},
		},
		callout = {
			note = {
				raw = "[!NOTE]",
				rendered = "󰋽 Note",
				highlight = "RenderMarkdownInfo",
				category = "github",
				quote_icon = "▍",
			},
			tip = {
				raw = "[!TIP]",
				rendered = "󰌶 Tip",
				highlight = "RenderMarkdownSuccess",
				category = "github",
				quote_icon = "▍",
			},
			important = {
				raw = "[!IMPORTANT]",
				rendered = "󰅾 Important",
				highlight = "RenderMarkdownError",
				category = "github",
				quote_icon = "▍",
			},
			warning = {
				raw = "[!WARNING]",
				rendered = "󰀪 Warning",
				highlight = "RenderMarkdownWarn",
				category = "github",
				quote_icon = "▍",
			},
			caution = {
				raw = "[!CAUTION]",
				rendered = "󰳦 Caution",
				highlight = "RenderMarkdownError",
				category = "github",
				quote_icon = "▍",
			},
			abstract = {
				raw = "[!ABSTRACT]",
				rendered = "󰨸 Abstract",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
				quote_icon = "▍",
			},
			summary = {
				raw = "[!SUMMARY]",
				rendered = "󰨸 Summary",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
				quote_icon = "▍",
			},
			tldr = {
				raw = "[!TLDR]",
				rendered = "󰨸 Tldr",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
				quote_icon = "▍",
			},
			info = {
				raw = "[!INFO]",
				rendered = "󰋽 Info",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
				quote_icon = "▍",
			},
			todo = {
				raw = "[!TODO]",
				rendered = "󰗡 Todo",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
				quote_icon = "▍",
			},
			hint = {
				raw = "[!HINT]",
				rendered = "󰌶 Hint",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
				quote_icon = "▍",
			},
			success = {
				raw = "[!SUCCESS]",
				rendered = "󰄬 Success",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
				quote_icon = "▍",
			},
			check = {
				raw = "[!CHECK]",
				rendered = "󰄬 Check",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
				quote_icon = "▍",
			},
			done = {
				raw = "[!DONE]",
				rendered = "󰄬 Done",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
				quote_icon = "▍",
			},
			question = {
				raw = "[!QUESTION]",
				rendered = "󰘥 Question",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
				quote_icon = "▍",
			},
			help = {
				raw = "[!HELP]",
				rendered = "󰘥 Help",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
				quote_icon = "▍",
			},
			faq = {
				raw = "[!FAQ]",
				rendered = "󰘥 Faq",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
				quote_icon = "▍",
			},
			attention = {
				raw = "[!ATTENTION]",
				rendered = "󰀪 Attention",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
				quote_icon = "▍",
			},
			failure = {
				raw = "[!FAILURE]",
				rendered = "󰅖 Failure",
				highlight = "RenderMarkdownError",
				category = "obsidian",
				quote_icon = "▍",
			},
			fail = {
				raw = "[!FAIL]",
				rendered = "󰅖 Fail",
				highlight = "RenderMarkdownError",
				category = "obsidian",
				quote_icon = "▍",
			},
			missing = {
				raw = "[!MISSING]",
				rendered = "󰅖 Missing",
				highlight = "RenderMarkdownError",
				category = "obsidian",
				quote_icon = "▍",
			},
			danger = {
				raw = "[!DANGER]",
				rendered = "󱐌 Danger",
				highlight = "RenderMarkdownError",
				category = "obsidian",
				quote_icon = "▍",
			},
			error = {
				raw = "[!ERROR]",
				rendered = "󱐌 Error",
				highlight = "RenderMarkdownError",
				category = "obsidian",
				quote_icon = "▍",
			},
			bug = {
				raw = "[!BUG]",
				rendered = "󰨰 Bug",
				highlight = "RenderMarkdownError",
				category = "obsidian",
				quote_icon = "▍",
			},
			example = {
				raw = "[!EXAMPLE]",
				rendered = "󰉹 Example",
				highlight = "RenderMarkdownHint",
				category = "obsidian",
				quote_icon = "▍",
			},
			quote = {
				raw = "[!QUOTE]",
				rendered = "󱆨 Quote",
				highlight = "RenderMarkdownQuote",
				category = "obsidian",
			},
			cite = {
				raw = "[!CITE]",
				rendered = "󱆨 Cite",
				highlight = "RenderMarkdownQuote",
				category = "obsidian",
				quote_icon = "▍",
			},
		},
		checkbox = {
			enabled = true,
			render_modes = false,
			bullet = false,
			left_pad = 0,
			right_pad = 1,
			unchecked = {
				icon = "󰄱 ",
				highlight = "RenderMarkdownUnchecked",
				scope_highlight = nil,
			},
			checked = {
				icon = "󰱒 ",
				highlight = "RenderMarkdownChecked",
				scope_highlight = "@markup.strikethrough",
			},
			scope_priority = nil,
		},
		dash = {
			enabled = true,
			render_modes = false,
			icon = "─",
			width = "full",
			left_margin = 0,
			highlight = "RenderMarkdownHint",
		},
		indent = {
			enabled = true,
			render_modes = "nc",
			per_level = 2,
			skip_level = 1,
			skip_heading = true,
			icon = false,
		},
		link = {
			enabled = true,
			hyperlink = "",
			custom = {},
		},
		code = {
			language_border = " ",
		},
	},
}
